### ISSUE TITLE
no gpu support?

### ISSUE THREAD

**Issue by dangelo352** [jllllll/bitsandbytes-windows-webui#1]
trying to use this with minigpt-4 
get this 
bin C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
Traceback (most recent call last):
  File "C:\MINIGPT\MiniGPT-4\demo.py", line 59, in <module>
    model = model_cls.from_config(model_config).to('cuda:0')
  File "C:\MINIGPT\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 241, in from_config
    model = cls(
  File "C:\MINIGPT\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 89, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\transformers\modeling_utils.py", line 2740, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

**Comment by jllllll** [comment]
What are you using to run MiniGPT-4? Whatever it is has the `BITSANDBYTES_NOWELCOME` environment variable set, which hides most of the debug information that bitsandbytes is meant to display. If I had to guess, you are likely using a CUDA Toolkit version that this wheel was not compiled for. It could also be an issue with Torch.

**Comment by dangelo352** [comment]
The default python command the minigpt-4 repo gives us anaconda i think

**Comment by dangelo352** [comment]
Also i have downloaded both the nvidia 11.6 cuda from their website and all the pytorch ive seen nothing has worked i just really wanna fix this.

**Comment by jllllll** [comment]
I looked at the environment.yml file on their repo and have an idea of what you can try.

Go into the Conda environment and run this:
```
conda install pytorch[version=1.12.1,build=py*_cuda11.6*] cuda-toolkit -c pytorch -c nvidia/label/cuda-11.6.0
```

**Comment by dangelo352** [comment]
yeah could i get a modified environment since I just tried and its causing conflicts with my current conda and every new conda requires I use their environment.yml

**Comment by jllllll** [comment]
Their environment.yml has such strict version requirements that I was unable to specify the cuda 11.6 build of Pytorch to install. This should still work, as 11.6 should be compatible with the 11.3 build that the original yml used. I included the bitsandbytes 0.38.1 wheel from this repo as well.

There may also need to be a more in-depth change in how to install their repo. In my short testing, I was unable to prevent the cpu version of Pytorch 2.0.0 from being installed, despite clearly defining 1.12.1. There appears to be some serious issues in how they have defined their environment, at least as far as Windows is concerned. I'll continue to do some testing and see if I can find a better way to install it.

I may just end up re-compiling the bitsandbytes wheel with cuda 11.3 support.
```YAML
name: minigpt4
channels:
  - pytorch
  - nvidia/label/cuda-11.6.0
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - cuda-toolkit
  - pip
  - pytorch=1.12.1[build=*cuda*]
  - pytorch-mutex=1.0=cuda
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip:
    - accelerate==0.16.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.38.1-py3-none-any.whl
    - cchardet==2.1.7
    - chardet==5.1.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - filelock==3.9.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - huggingface-hub==0.13.4
    - importlib-resources==5.12.0
    - kiwisolver==1.4.4
    - matplotlib==3.7.0
    - multidict==6.0.4
    - openai==0.27.0
    - packaging==23.0
    - psutil==5.9.4
    - pycocotools==2.0.6
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - regex==2022.10.31
    - tokenizers==0.13.2
    - tqdm==4.64.1
    - transformers==4.28.0
    - timm==0.6.13
    - spacy==3.5.1
    - webdataset==0.2.48
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - yarl==1.8.2
    - zipp==3.14.0
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - iopath==0.1.10
    - decord==0.6.0
    - tenacity==8.2.2
    - peft
    - pycocoevalcap
    - sentence-transformers
    - umap-learn
    - notebook
    - gradio==3.24.1
    - gradio-client==0.0.8
    - wandb
```

**Comment by dangelo352** [comment]
i uninstalled anaconda reinstalled it then made a whole new environment with the one you provided and got this 
(minigpt4) C:\MINIGPT\MiniGPT-4>python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\__main__.py", line 49, in generate_bug_report_information
    paths = find_file_recursive(os.environ['CONDA_PREFIX'], '*cuda*so')
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

(minigpt4) C:\MINIGPT\MiniGPT-4>

**Comment by jllllll** [comment]
I'm currently re-compiling the the bitsandbytes 0.38.1 wheel with cuda 11.3 support. This should allow you to use the original environment.yml. Afterwards, I'll re-compile the 0.37.2 wheel just in case that is needed.

**Comment by dangelo352** [comment]
okay ill be waiting thank you so much

**Comment by jllllll** [comment]
I added 11.3 support, but this seems to be a much more deeply rooted issue with their environment.yml. One or more of the pip requirements listed are incompatible with the version of pytorch they are trying to use. This causes the latest version of torch to get installed by pip, which is incompatible with cuda 11.3. This causes you to end up with the cpu version of torch that is incompatible with pretty much everything else.

Can you try this yml? It has newer versions of the torch packages. I would try it myself, except I don't have the VRAM to use the MiniGPT-4 models.
```YAML
name: minigpt4
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - cuda-toolkit
  - pip
  - pytorch[version=2,build=py*_cuda*]
  - pytorch-mutex=1.0=cuda
  - torchaudio
  - torchvision
  - pip:
    - accelerate==0.16.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.38.1-py3-none-any.whl
    - cchardet==2.1.7
    - chardet==5.1.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - filelock==3.9.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - huggingface-hub==0.13.4
    - importlib-resources==5.12.0
    - kiwisolver==1.4.4
    - matplotlib==3.7.0
    - multidict==6.0.4
    - openai==0.27.0
    - packaging==23.0
    - psutil==5.9.4
    - pycocotools==2.0.6
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - regex==2022.10.31
    - tokenizers==0.13.2
    - tqdm==4.64.1
    - transformers==4.28.0
    - timm==0.6.13
    - spacy==3.5.1
    - webdataset==0.2.48
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - yarl==1.8.2
    - zipp==3.14.0
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - iopath==0.1.10
    - decord==0.6.0
    - tenacity==8.2.2
    - peft
    - pycocoevalcap
    - sentence-transformers
    - umap-learn
    - notebook
    - gradio==3.24.1
    - gradio-client==0.0.8
    - wandb
```
